apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: sck-reproducer
servers: 1
image: rancher/k3s:v1.31.1-k3s1
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=coredns,local-storage,metrics-server,traefik
        nodeFilters:
          - all
